name: ChineseName
main: main.main
version: 2.4-happyeveryday-xD
author: "§b小雨"
description: "§b§l反馈群426996480"
commands:
  ChineseName:
    aliases:
      - cn
    description: "使用/cn help 页码 查看帮助"
permissions:
  cn.usecard:
    default: true
